AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create an S3 bucket with a dynamic name and region'

Parameters:
  BucketName:
    Type: String
    Description: 'The name of the S3 bucket'

  RegionName:
    Type: String
    Description: 'The AWS region where the bucket will be created'

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: "The created S3 bucket name"


